### ISSUE TITLE
Woodbury solve for Hierarchical GreensFun

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SingularIntegralEquations.jl#28]
We have a method `woodburysolve` for `HierarchicalMatrix{S<:AbstractMatrix,T<:LowRankMatrix}` objects, and we have a `hierarchicalGreensFun` method with hierarchically off-diagonal `LowRankFun`s. Ideally, the recursive `woodburysolve` should work on all hierarchically off-diagonal low-rank forms, it's just a matter of assigning the right meanings to the algebraic symbols.

What happens when we `getindex` a `DefiniteLineIntegral` with a `HierarchicalMatrix{GreensFun,GreensFun{LowRankFun}}`?

Should there be a `LowRankOperator`? Then one possible result would be a `HierarchicalMatrix{Operator,LowRankOperator}`.

**Comment by MikaelSlevinsky** [comment]
I profiled this code:
```julia
using ApproxFun, SingularIntegralEquations

import SingularIntegralEquations: woodburysolve

dom = cantor(Interval(),6)
⨍ = DefiniteLineIntegral(dom)
G = GreensFun((x,y)->1/2,CauchyWeight(Space(dom)⊗Space(dom),0);method=:Cholesky)
f = Fun(x->logabs(x-5im),dom)

⨍[G]\transpose(f)
gc()
gc_disable()
@time u1 = ⨍[G]\transpose(f)
gc_enable()
gc()

println("Adaptive QR  forward error norm is: ",norm(⨍[G]*u1-f))


G1 = GreensFun((x,y)->1/2,CauchyWeight(Space(dom)⊗Space(dom),0);method=:hierarchical)
H = ⨍[G1]

woodburysolve(H,f)
gc()
gc_disable()
@time u3 = woodburysolve(H,f)
gc_enable()
gc()

println("The Woodbury forward error norm is: ",norm(⨍[G]*u3-f))
```

I found that if I make this change in ApproxFun's linsolve:
```julia
            #cfsB=Vector{typ}[coefficients(b[end,k],rs) for k=1:size(b,2)]
            cfsB=Vector{typ}[coefficients(b[end,k]) for k=1:size(b,2)]
```
on [this](https://github.com/ApproxFun/ApproxFun.jl/blob/development/src/Operators/linsolve.jl#L86) line, the timings go from:
```julia
julia> include("woodburysolve.jl")
elapsed time: 12.823110376 seconds (545133248 bytes allocated)
Adaptive QR  forward error norm is: 4.580157263439304e-13
elapsed time: 24.606177107 seconds (7320499616 bytes allocated)
The Woodbury forward error norm is: 9.638141733282976e-8
```
to:
```julia
julia> include("woodburysolve.jl")
elapsed time: 12.660680868 seconds (545107112 bytes allocated)
Adaptive QR  forward error norm is: 4.580157263439304e-13
elapsed time: 2.403952018 seconds (1310053640 bytes allocated)
The Woodbury forward error norm is: 9.638141730117499e-8
```

The b spaces are Chebyshev() and the rangespaces are also Chebyshev(), so I found that the offending line was sending all the coefficients through the chebyshevtransform!!!

**Comment by MikaelSlevinsky** [comment]
I should mention that this is on branch feat-hierarchies.

**Comment by dlfivefifty** [comment]
Hmm, if rs is the same space the two lines should be equivalent..so there shouldn't be a chebyshevtransform unless there's an error in the various coefficients routines

**Comment by MikaelSlevinsky** [comment]
I'm not sure, but I think it's because `b::Array{Any}`, so it doesn't know it's in `Chebyshev()`. Possible?

**Comment by MikaelSlevinsky** [comment]
No, there's something else going on.

**Comment by dlfivefifty** [comment]
Hmm, but I do wonder how much overhead is caused by Array{Any}. 

	linsolve(functionals,ops,bcs,f)

may be better, with tuples for the arguments?

**Comment by MikaelSlevinsky** [comment]
It turns out the linsolve line is OK with the [latest fix](https://github.com/ApproxFun/SingularIntegralEquations.jl/commit/2e1d07f5c53e135cc975df80c74de8d97277a48b) to woodburysolve. I'm now getting:
```julia
julia> include("woodburysolve.jl")
elapsed time: 12.660787833 seconds (545119400 bytes allocated)
Adaptive QR  forward error norm is: 4.580157263439304e-13
elapsed time: 1.917063256 seconds (1216687672 bytes allocated)
The Woodbury forward error norm is: 9.638141730117499e-8
```

**Comment by dlfivefifty** [comment]
So do you see the linear complexity in the timings?? 6400 domains in 200 seconds sounds pretty good! 😀

**Comment by MikaelSlevinsky** [comment]
No I think there's still something to be gained vis-à-vis scaling, but the typing issue is gone so I'm happy for today!

**Comment by MikaelSlevinsky** [comment]
Had a go at rewriting the solver to incorporate a precomputation of the pivot matrices with another significant speed increase but the solver is still computing from the top down. I think if it goes bottom up, then it will be linear in the number of domains.

**Comment by MikaelSlevinsky** [comment]
Using this [script](https://gist.github.com/MikaelSlevinsky/725d8c17ee73bf565c48.js), I'm getting this timing plot. Are we sure adaptive QR scales as d^2? or is it d^3?

blue dash is d^3, black dash is d^2, red is adaptive QR interlaced, green is hierarchical solve.

![timingtestslaplace](https://cloud.githubusercontent.com/assets/8176037/9690898/044e94de-5337-11e5-8dcf-8c72d479b27e.png)

**Comment by dlfivefifty** [comment]
Fantastic!!

It's nd^2 but n is necessary at least d, so yes, at least d^3.

**Comment by dlfivefifty** [comment]
If you do the plot down to d = 1, when is the cross over?

**Comment by MikaelSlevinsky** [comment]
For one domain, the algorithm (which needs a better name, perhaps `hierarchicalsolve`?) has the fallbacks
```julia
woodburysolve{V<:Operator}(H::V,f::Fun) = H\f
woodburysolve{V<:Operator,F<:Fun}(H::V,f::Vector{F}) = vec(H\transpose(f))
```
so the timings would meet. This plot is an ideal example where the on-diagonal operators have bandwidth 0, i.e. Laplace equation.

For on-diagonal operators with SingularIntegral + low-rank structure, we could also implement the Woodbury matrix identity.

**Comment by dlfivefifty** [comment]
BandedOperator + LowRankOperator would be really useful for Curve’s, which have a compact perturbation.

	Though it’s possible that something more stable than Woodbury can be done.  I’m thinking something along the lines of doing QR on the dense part of the operator, and then adaptive QR on the remaining small bandwidth part.

**Comment by MikaelSlevinsky** [comment]
Cool! Yes, This shows up for the scattering problems as well. The singular integral operators have a large block at the top (which ultimately overdetermines the bandwidth later on) and a smaller bandwidth part that continues infinitely. Jared mentioned that exact idea to me a while ago.

By the way, isn't LowRankOperator is not necessarily compact?

Cheers,

Mikael

**Comment by dlfivefifty** [comment]
LowRankOperator should always be compact in the mathematical sense provided the spaces are chosen carefully:  Compact means Bounded + finite rank, and the spaces could be chosen so that, even if there are dense functionals, these are bounded.

 CompactOperator is much stronger than a compact operator.  (CompactOperator should probably be renamed FiniteOperator or MatrixOperator or similar.)

There is a notion of low rank operator that I can’t see being supported in the near future: one could have an outer product of dense functionals:

		functional’*functional 

for example, rdirichlet(Chebyshev())’rdirichlet(Chebyshev())  is the matrix of all ones.

**Comment by MikaelSlevinsky** [comment]
OK, I think I understand. My point was that the last notion is something that the data type LowRankOperator might be extended to support, but we don't have an algorithm to solve for such operators: adaptive QR is inapplicable because it's not banded, and if it were disassembled via a low-rank matrix identity, adaptive QR can't back-solve against the operator's columns anyway (whose coefficients don't tend to 0). Is that right?

Maybe Householder reflectors would be more compatible with the LowRankOperator. They may benefit from vectorized BLAS subroutines. What if it's possible to store entries of the BandedOperator and LowRankOperator in distinct concrete data types, only combine them when preparing to zero entries and otherwise perform the unitary transformations on both separately?

**Comment by MikaelSlevinsky** [comment]
Should we rename the current LowRankOperator to CompactOperator with the assumptions of finite-rank and bounded functionals?

It's not clear what low rank means for an operator. For a matrix it's probably somewhere and for a function it's defined in Alex's thesis.

**Comment by dlfivefifty** [comment]
Maybe, and adding MatrixOperator.  This could be facilitated by

	CompactOperator(::Matrix)

calling

	MatrixOperator(::Matrix)

since conceptually a MatrixOperator is a special case of CompactOperator.

Or probably CompactOperator should be an abstract type which supports different variants, to be consistent with the broader mathematical definition.  One could imagine implementing an operator with 1/k decay and labeling it a CompactOperator.

We should probably also have a TraceClassOperator.
