### ISSUE TITLE
change cauchy(s,f,z) to cauchy(f,z,s) to make implementation easier?

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/SingularIntegralEquations.jl#31]
Many pass through functions would be easier to implement via e.g.

cauchy(f,z,s...)=stieltjes(f,z,s...)/(-2π*im)

**Comment by dlfivefifty** [comment]
Other option is to get rid of s definition in favour of embedding orientation inside z, something like dual(1,false)

**Comment by MikaelSlevinsky** [comment]
Sounds reasonable to me. Is it possible to write a macro that vectorizes a function that takes a first argument, then a vector? Perhaps @vectorize_object_1arg and @vectorize_object_2arg macros would shorten some ApproxFun code.

**Comment by MikaelSlevinsky** [comment]
Sorry I meant to refer to the first option. Wouldn't dual numbers for `z::Array` be excessive when `s` is really just a behaviour toggle?

**Comment by dlfivefifty** [comment]
yep I think you are right

**Comment by MikaelSlevinsky** [comment]
Would it be of any use for cauchy(f,z::Array{Dual}) to compute both +1 and -1?

Cheers,

Mikael

**Comment by dlfivefifty** [comment]
Maybe!  But I think we would want to interpret it as 

	dual(z,exp(im*θ))

and then determine based on θ whether s=true or s=false. 

But evaluating at a dual number should also return the derivative, so cauchy(f,z::Array{Dual}) would return an Array of Duals, and real(cauchy(f,z::Array{Dual})) would give the values.    (There is an unfortunate use of the term “real” in Dual.)
