### ISSUE TITLE
TypeError when running examples in Julia v 0.4

### ISSUE THREAD

**Issue by mgr58** [ApproxFun/SingularIntegralEquations.jl#37]
julia /home/xxx/.julia/v0.4/SingularIntegralEquations/examples/erfc.jl

WARNING: module ApproxFun should explicitly import getindex from Base
... bunch of warnings from ApproxFun deleted to save some space ...
WARNING: module ApproxFun should explicitly import transpose from Base
ERROR: LoadError: LoadError: LoadError: LoadError: TypeError: CauchyWeight: in parameter, expected Type{T}, got Tuple{TypeVar,TypeVar}
while loading /home/xxx/.julia/v0.4/SingularIntegralEquations/src/./GreensFun/CauchyWeight.jl, in expression starting on line 15
while loading /home/xxx/.julia/v0.4/SingularIntegralEquations/src/./GreensFun/GreensFun.jl, in expression starting on line 1
while loading /home/xxx/.julia/v0.4/SingularIntegralEquations/src/SingularIntegralEquations.jl, in expression starting on line 51
while loading /home/xxx/.julia/v0.4/SingularIntegralEquations/examples/erfc.jl, in expression starting on line 8

Version information:

julia> versioninfo()
Julia Version 0.4.0-pre+7303
Commit 404b414* (2015-09-05 05:01 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by MikaelSlevinsky** [comment]
Thanks!

The ApproxFun suite is currently developed in Julia v0.3.x and will be until the first v0.4 release. Does it work for you in 0.3?

Cheers,

Mikael

**Comment by dlfivefifty** [comment]
I’ve started switching over to 0.4 (which ApproxFun works fine in.  0.4 really helps reduce compile-time induced suicidal thoughts), so I’ll have a go at fixing this bug.

Sheehan

**Comment by dlfivefifty** [comment]
This ran into a problem with (LowRankOperator.jl)

immutable LowRankOperator{S<:FunctionSpace,M<:FunctionSpace,T1,T2} <: InfiniteOperator{promote_type(T1,T2)}


I asked if there is an 0.4 equivalent

		https://groups.google.com/forum/?fromgroups=#!topic/julia-users/9OdU6d7_ogo <https://groups.google.com/forum/?fromgroups=#!topic/julia-users/9OdU6d7_ogo>


otherwise, maybe it should be restructured to only have one T, and promote the type of U and V first.

**Comment by MikaelSlevinsky** [comment]
LowRankOperator only has one type T now! Promotions now occur in an outer constructor.

**Comment by dlfivefifty** [comment]
This is now held up by a segmentation fault bug in 0.4:

https://github.com/JuliaLang/julia/issues/13007#issuecomment-138396086

**Comment by dlfivefifty** [comment]
This should now work!

**Comment by dlfivefifty** [comment]
Just make sure you

Pkg.checkout("ApproxFun","development")

**Comment by mgr58** [comment]
Thank you!

Confirming that it works with Julia 0.4.0-pre+7397 (2015-09-08 18:44 UTC Commit c252788*). 

As a side comment, in order to succeed in  Pkg.build("SingularIntegralEquations") it was necessary to rename the compiler in SingularIntegralEquations/deps/Makefile from gcc-5 to gcc (gcc is the name that is used on Linux) and uncomment all lines that define M_PI related constants at the top of fundsol.c. (or use a compiler option) - see e.g. the first answer in the discussion http://stackoverflow.com/questions/5007925/using-m-pi-with-c89-standard

**Comment by dlfivefifty** [comment]
I think we are going to remove the build step at some point.  The package doesn't need it
