### ISSUE TITLE
Plotting of small domains

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SingularIntegralEquations.jl#41]
```julia
using ApproxFun, SingularIntegralEquations, PyPlot
d(i) = cantor(Interval(),i)+0im
ApproxFun.plot(d(5);color="black")
savefig("test5.png";dpi=300,bbox_inches="tight")
clf()
ApproxFun.plot(d(6);color="black")
savefig("test6.png";dpi=300,bbox_inches="tight")
```
Results are the same:
![test5](https://cloud.githubusercontent.com/assets/8176037/9757488/e06fb138-56d8-11e5-8c7f-f49899345038.png)
![test6](https://cloud.githubusercontent.com/assets/8176037/9757489/e08a7db0-56d8-11e5-8759-748d9edc31c6.png)

**Comment by dlfivefifty** [comment]
you could use Gadfly

**Comment by MikaelSlevinsky** [comment]
Indeed, Gadfly does the trick. I wish I knew how to use it better. I'd like to be able to choose the colour of the domains I plot, and also add a contour plot before/plotting domains (I think this must be done via layers? but surely ApproxFun could have a simple API)
