### ISSUE TITLE
Should Base.getindex(::Operator,::LowRankFun) return a LowRankOperator? / Where is the overhead?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SingularIntegralEquations.jl#47]
Should Base.getindex(::Operator,::LowRankFun) return a LowRankOperator?

Perhaps a better formula for LowRankOperator leaves the types of U and V (and possibly C) more free. Maybe V could be more than just a list of functionals. Yet, if they had a common operator, it would be more efficient to store it as C, rather than copy it to each element of V as some kind of FunctionalWrapper.

Where is the overhead?

Off the readme:
```julia
using ApproxFun, SingularIntegralEquations
k = 50 # Set wavenumber and fundamental solution for Helmholtz equation
g1(x,y) = -besselj0(k*abs(y-x))/2
g2(x,y) = x == y ? -(log(k/2)+γ)/2/π + im/4 : im/4*hankelh1(0,k*abs(y-x)) - g1(x,y).*logabs(y-x)/π

ui(x,y) = exp(im*k*(x-y)/sqrt(2))    # Incident plane wave at 45°

dom = Interval()                     # Set the domain
sp = Space(dom)                      # Canonical space on the domain
⨍ = DefiniteLineIntegral(dom)        # Line integration functional
uiΓ = Fun(t->ui(real(t),imag(t)),sp) # Incident wave on Γ

# Instantiate the fundamental solution
G = GreensFun(g1,CauchyWeight(sp⊗sp,0)) + GreensFun(g2,sp⊗sp)
```
It's quicker to do a dense QR factorization on the entries. (note no adaptivity)
```julia
julia> @time ∂u∂n = ⨍[G]\uiΓ;
  2.659190 seconds (575.29 k allocations: 401.028 MB, 2.05% gc time)

julia> @time begin
           QR = qrfact(full(⨍[G][1:length(∂u∂n),1:length(∂u∂n)]))
           sol = QR\pad(coefficients(uiΓ),length(∂u∂n))
       end;
  0.418481 seconds (572.62 k allocations: 152.076 MB, 6.08% gc time)
```

**Comment by dlfivefifty** [comment]
Conceptually it only makes sense for V to be functionals, though maybe when they are finite it's better to store U and V as matrices and add domainspace and rangespace fields.

**Comment by MikaelSlevinsky** [comment]
I think a lot of this has been addressed in the last year.
