### ISSUE TITLE
cauchy(f,z,+1)/cauchy(f,z,-1) -> cauchy(f,z,+)/cauchy(f,z,-)

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/SingularIntegralEquations.jl#57]
Right now s=+1 => s=true and s=-1 => s=false.   I think it should work via s=+ => true and s=- => false.  This avoids the issue that true==1 and false ==0.

**Comment by MikaelSlevinsky** [comment]
:+1:
