### ISSUE TITLE
update dotu/linedotu/dot/linedot

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SingularIntegralEquations.jl#66]
After ApproxFun/ApproxFun.jl@8b31c1f78c68cbeb073c6291f7fae6912e78e544, these need updating to `bilinearform` and `innerproduct`.

**Comment by dlfivefifty** [comment]
OK I can fix this.  Are you happy with bilinearform and innerproduct?  or would, say, innerproduct and cinnerproduct be better?

**Comment by MikaelSlevinsky** [comment]
They're fine by me.
