### ISSUE TITLE
Use new BandedMatrix \ for large bandwidth solves

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/SingularIntegralEquations.jl#68]
I think the following timing suggests that we would perform significantly better using truncation and banded matrix :

``` julia
#HelmholtzDirichlet.jl example
@time ∂u∂n = ⨍[G]\uiΓ   # 6.882111 seconds (20.04 M allocations: 4.365 GB, 10.21% gc time)
cfs=pad(coefficients(uiΓ,rangespace(⨍[G])),100)
@time ⨍[G][1:100,1:100]\cfs  # 0.786749 seconds (2.67 M allocations: 525.196 MB, 10.94% gc time)

```

It's based on LU, so there may be inaccuracies introduced, but in this case they match to `8.9e-12`

**Comment by dlfivefifty** [comment]
For `k=0.1` the two are tied!  (Probably the cost is dominated by constructing the operator)

```julia
@time ∂u∂n = ⨍[G]\uiΓ    # 0.001622 seconds (9.53 k allocations: 871.625 KB)
@time u=⨍[G][1:10,1:10]\cfs  # 0.001138 seconds (4.63 k allocations: 306.406 KB)
```

**Comment by MikaelSlevinsky** [comment]
It could even use a Cholesky factorization for (formally) positive definite fundamental solutions.

**Comment by dlfivefifty** [comment]
I think the new `qrfact` mitigates the benefits of doing this automatically.
